#!/usr/bin/env bash
set -e

config_dir=$(pwd)/$1

script_path=$(dirname "${BASH_SOURCE[0]}")
source $script_path/common > /dev/null

cd $provisioner_dir/aws

terraform destroy \
    -var-file=$config_dir/terraform.tfvars \
    -state=$config_dir/terraform.tfstate

rm -f $config_dir/terraform.tfstate*
